name: Keep Backend Awake

on:
  schedule:
    # Runs every 20 minutes
    - cron: "*/20 * * * *"
  workflow_dispatch:  # lets you trigger manually too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call backend URL
        run: |
          curl -s -o /dev/null -w "%{http_code}\n"https:// back-autosocialize.onrender.com
