name: Keep Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 10 minutes
  workflow_dispatch:          # allows manual runs too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call backend URL
        run: |
          echo "[$(date)] Pinging backend..."
          curl -s -o /dev/null -w "Status: %{http_code}\n" https://back-autosocialize.onrender.com
